version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository npm-store --domain conrisc --domain-owner 118101356080
  build:
    commands:
      - echo Build started on `date`
      - yarn install --network-concurrency 1
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*
  discard-paths: yes
